global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics exposed by the collector's Prometheus exporter
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  # Scrape native Prom metrics endpoint
  - job_name: 'stacklion-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
